### ISSUE TITLE
CICD pipe flow 설정

### ISSUE THREAD

**Issue by Jeong-Rae** [PhantomOfLINUX/MasterServer#9]
## Title
> CICD pipe flow 설정

## Description
> PR과 Merge에 따른 flow를 분리한다.

### Task
- [x] PR : 빌드와 TEST만 실행
- [x] Merge: build 후 deploy
- [x] Cache: Merge시에는 build 결과물 캐싱
